version: '3.7'

networks:
  site-config-network:
    name: site-config-network
    driver: bridge
services:
  # app:
  #   image: site-config:1.0.0
  #   container_name: site-config-springboot
  #   build: ./springboot/
  #   ports:
  #     - "8081:8080"
  #   networks:
  #     - site-config-network
  #   depends_on:
  #     - db
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/learning_fridays
  #     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:?}
  #     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:?}
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:14.2-alpine
    container_name: site-config-postgres
    volumes:
      - ${POSTGRES_DATA:?}:/var/lib/postgresql/data
    networks:
      - site-config-network
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=site-config-postgres
      